#!/bin/bash

echo "Contents of $HOME/install/deps/include/" >&2
ls $HOME/install/deps/include/ >&2

echo "Contents of $HOME/install/deps/include/openjpeg-2.5" >&2
ls $HOME/install/deps/include/openjpeg-2.5 >&2

expected_deps_count="$1"
deps_installed="$(find . -name '*-install-stamp')"
num_deps_installed=$(echo "$deps_installed" | sed '/^\s*$/d' | wc -l)
echo "Dependencies installed $num_deps_installed, expected $expected_deps_count" >&2
echo "$deps_installed" >&2
if test $num_deps_installed -ne $expected_deps_count
then echo "Unexpected number of dependencies installed! Found $num_deps_installed, expected $expected_deps_count";
    exit 1;
fi
