# This is a basic workflow to help you get started with Actions

name: CI

env:
  prefix: ${{ github.workspace }}/build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ actions-test, master ]
  pull_request:
    branches: [ actions-test, master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel

jobs:
  # Build on OSX just to check that changes work in our dev environments
  osx-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: make as developers will
        run: make -j8
