# This is a basic workflow to help you get started with Actions

name: CI-CentOS-7

env:
  prefix: ${{ github.workspace }}/build
  threads: 16

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ actions-test, master ]
  pull_request:
    branches: [ actions-test, master ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel

jobs:
  # For info on the docker commands: https://www.petefreitag.com/item/903.cfm
  # and https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions
  # This build uses Ubuntu link to run Docker and a CentOS7 container
  # for the build. Note that commands run inside the container.
  centos-7-build:
    runs-on: ubuntu-latest
    container:
      image: opendap/centos7_hyrax_builder:1.3

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: make static dependency libraries
        run: |
          make --jobs=$threads for-static-rpm
          ls -lR $prefix/deps
      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: $prefix/deps
          name: hyrax-centos7-deps.zip
