# This is a basic workflow to help you get started with Actions

name: CI

env:
  prefix: ${{ github.workspace }}/build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ actions-test ]

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: make-for-actions
        run: make -j16 for-actions

      - run: ls -lR

  centos-build:
    runs-on: centos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: make-for-actions
        run: make -j16 for-actions

      - run: ls	-lR

