# This is a basic workflow to help you get started with Actions

name: CI

env:
  prefix: ${{ github.workspace }}/build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ actions-test ]
  pull_request:
    branches: [ actions-test ]

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: make-for-actions
        run: make -j16 for-actions

      - run: ls -lR

  osx-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: make-for-actions
        run: make -j16 for-actions

      - run: ls	-lR

  # For info on the docker commands: https://www.petefreitag.com/item/903.cfm
  testbox:
    runs-on: ubuntu-latest
    container:
      image: opendap/centos7_hyrax_builder:1.1
      # azul/zulu-openjdk-alpine:8-jre
    steps:
      - uses: actions/checkout@v2
      - name: What OS is running
        run: uname -a
      - name: What g++ version do we have
        run: g++ --version
